# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BestELD' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BestELD
  pod 'L10n-swift', '~> 5.7'

end
